services:
  - type: web
    name: recipe-project-backend
    env: node
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: JWT_SECRET
        generateValue: true
      - key: SPOONACULAR_API_KEY
        sync: false
    plan: free # Ensure this is set to 'free'

  - type: web
    name: recipe-project-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://recipe-project-backend.onrender.com
    plan: free # Ensure this is set to 'free'
