name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install dependencies
        run: |
          rm -f package-lock.json
          npm install --legacy-peer-deps
      - name: Run tests
        run: npm test -- --watchAll=false
